openapi: 3.0.0
info:
  title: W03 CRUD API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/products:
    get:
      summary: List products
      responses:
        '200':
          description: OK
    post:
      summary: Create product
      requestBody:
        required: true
      responses:
        '201':
          description: Created
  /api/products/{id}:
    get:
      summary: Get product by id
      parameters:
        - name: id
          in: path
          required: true
    put:
      summary: Update product
    delete:
      summary: Delete product
  /api/orders:
    get:
      summary: List orders
    post:
      summary: Create order
  /api/orders/{id}:
    get:
      summary: Get order
    put:
      summary: Update order
    delete:
      summary: Delete order
