openapi: 3.0.0
info:
  title: W03 CRUD API
  version: 1.0.0

servers:
  - url: https://proyectcrud.onrender.com
    description: API desplegada en Render

paths:
  # ===== Productos =====
  /api/products:
    get:
      summary: List products
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Filtrar productos por nombre
      responses:
        '200':
          description: Success
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Product created

  /api/products/{id}:
    delete:
      summary: Delete a product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto a eliminar
      responses:
        '200':
          description: Product deleted

  # ===== Órdenes =====
  /api/orders:
    get:
      summary: List orders
      parameters:
        - in: query
          name: customer
          schema:
            type: string
          description: Filtrar órdenes por cliente
      responses:
        '200':
          description: Success
    post:
      summary: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerName:
                  type: string
                product:
                  type: string
                quantity:
                  type: integer
      responses:
        '201':
          description: Order created

  /api/orders/{id}:
    delete:
      summary: Delete an order
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la orden a eliminar
      responses:
        '200':
          description: Order deleted
