openapi: 3.0.0
info:
  title: CRUD API Project
  version: 1.0.0
  description: API con operaciones CRUD para Products y Orders

servers:
  - url: https://proyectcrud.onrender.com

paths:
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Lista de productos
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Producto creado

  /api/products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
        '404':
          description: Producto no encontrado
    put:
      summary: Update a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '200':
          description: Producto actualizado
        '404':
          description: Producto no encontrado
    delete:
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado
        '404':
          description: Producto no encontrado

  /api/orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: Lista de órdenes
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - quantity
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
      responses:
        '201':
          description: Orden creada

  /api/orders/{id}:
    get:
      summary: Get an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Orden encontrada
        '404':
          description: Orden no encontrada
    put:
      summary: Update an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Orden actualizada
        '404':
          description: Orden no encontrada
    delete:
      summary: Delete an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Orden eliminada
        '404':
          description: Orden no encontrada
