openapi: 3.0.0
info:
  title: W03 CRUD API
  version: 1.0.0

servers:
  - url: https://proyectcrud.onrender.com
    description: API desplegada en Render

paths:
  /api/products:
    get:
      summary: List products
      responses:
        '200':
          description: Success
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Product created
    delete:
      summary: Delete a product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto a eliminar
      responses:
        '200':
          description: Product deleted

  /api/orders:
    get:
      summary: List orders
      responses:
        '200':
          description: Success
    post:
      summary: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerName:
                  type: string
                product:
                  type: string
                quantity:
                  type: integer
      responses:
        '201':
          description: Order created
    delete:
      summary: Delete an order
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          descr
