openapi: 3.0.0
info:
  title: Proyecto CRUD API
  version: 1.0.0
  description: API con CRUD completo para productos y órdenes
servers:
  - url: https://proyectcrud.onrender.com
paths:
  /api/products:
    get:
      summary: Listar productos
      responses:
        '200':
          description: Lista de productos obtenida correctamente
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                stock:
                  type: number
      responses:
        '201':
          description: Producto creado correctamente

  /api/products/{id}:
    put:
      summary: Actualizar producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                stock:
                  type: number
      responses:
        '200':
          description: Producto actualizado
    delete:
      summary: Eliminar producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado

  /api/orders:
    get:
      summary: Listar órdenes
      responses:
        '200':
          description: Lista de órdenes obtenida correctamente
    post:
      summary: Crear una nueva orden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: number
                total:
                  type: number
      responses:
        '201':
          description: Orden creada correctamente

  /api/orders/{id}:
    put:
      summary: Actualizar orden por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: number
                total:
                  type: number
      responses:
        '200':
          description: Orden actualizada correctamente
    delete:
      summary: Eliminar orden por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Orden eliminada correctamente
